require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiscountCodesController do

  # This should return the minimal set of attributes required to create a valid
  # DiscountCode. As you add validations to DiscountCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiscountCodesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all discount_codes as @discount_codes" do
      discount_code = DiscountCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:discount_codes).should eq([discount_code])
    end
  end

  describe "GET show" do
    it "assigns the requested discount_code as @discount_code" do
      discount_code = DiscountCode.create! valid_attributes
      get :show, {:id => discount_code.to_param}, valid_session
      assigns(:discount_code).should eq(discount_code)
    end
  end

  describe "GET new" do
    it "assigns a new discount_code as @discount_code" do
      get :new, {}, valid_session
      assigns(:discount_code).should be_a_new(DiscountCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested discount_code as @discount_code" do
      discount_code = DiscountCode.create! valid_attributes
      get :edit, {:id => discount_code.to_param}, valid_session
      assigns(:discount_code).should eq(discount_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DiscountCode" do
        expect {
          post :create, {:discount_code => valid_attributes}, valid_session
        }.to change(DiscountCode, :count).by(1)
      end

      it "assigns a newly created discount_code as @discount_code" do
        post :create, {:discount_code => valid_attributes}, valid_session
        assigns(:discount_code).should be_a(DiscountCode)
        assigns(:discount_code).should be_persisted
      end

      it "redirects to the created discount_code" do
        post :create, {:discount_code => valid_attributes}, valid_session
        response.should redirect_to(DiscountCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved discount_code as @discount_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        DiscountCode.any_instance.stub(:save).and_return(false)
        post :create, {:discount_code => {}}, valid_session
        assigns(:discount_code).should be_a_new(DiscountCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DiscountCode.any_instance.stub(:save).and_return(false)
        post :create, {:discount_code => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested discount_code" do
        discount_code = DiscountCode.create! valid_attributes
        # Assuming there are no other discount_codes in the database, this
        # specifies that the DiscountCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DiscountCode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => discount_code.to_param, :discount_code => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested discount_code as @discount_code" do
        discount_code = DiscountCode.create! valid_attributes
        put :update, {:id => discount_code.to_param, :discount_code => valid_attributes}, valid_session
        assigns(:discount_code).should eq(discount_code)
      end

      it "redirects to the discount_code" do
        discount_code = DiscountCode.create! valid_attributes
        put :update, {:id => discount_code.to_param, :discount_code => valid_attributes}, valid_session
        response.should redirect_to(discount_code)
      end
    end

    describe "with invalid params" do
      it "assigns the discount_code as @discount_code" do
        discount_code = DiscountCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DiscountCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => discount_code.to_param, :discount_code => {}}, valid_session
        assigns(:discount_code).should eq(discount_code)
      end

      it "re-renders the 'edit' template" do
        discount_code = DiscountCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DiscountCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => discount_code.to_param, :discount_code => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested discount_code" do
      discount_code = DiscountCode.create! valid_attributes
      expect {
        delete :destroy, {:id => discount_code.to_param}, valid_session
      }.to change(DiscountCode, :count).by(-1)
    end

    it "redirects to the discount_codes list" do
      discount_code = DiscountCode.create! valid_attributes
      delete :destroy, {:id => discount_code.to_param}, valid_session
      response.should redirect_to(discount_codes_url)
    end
  end

end
